[package]
name = "server-script"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.6", features = ["blocking", "stream"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
futures = "0.3.18"
tokio = { version = "1.14.0", features = ["full"] }
ansi_term = "0.12.1"
regex = "1.5.4"